# Generated by Django 5.2.14 on 2026-06-02 21:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_at', models.DateTimeField(help_text='Fecha y hora programada de entrega (aware datetime).')),
                ('supplier', models.CharField(choices=[('A', 'Proveedor A'), ('B', 'Proveedor B'), ('C', 'Proveedor C')], max_length=1)),
                ('product_line', models.CharField(choices=[('Camisetas', 'Camisetas'), ('Pantalones', 'Pantalones'), ('Zapatos', 'Zapatos'), ('Accesorios', 'Accesorios')], max_length=20)),
                ('status', models.CharField(choices=[('Programada', 'Programada'), ('En proceso', 'En proceso'), ('Entregada', 'Entregada'), ('Cancelada', 'Cancelada')], default='Programada', max_length=15)),
                ('delivered_at', models.DateTimeField(blank=True, help_text="Fecha y hora real de entrega; requerida si 'Entregada'.", null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'appointments',
                'ordering': ['-scheduled_at'],
                'indexes': [models.Index(fields=['scheduled_at'], name='idx_appt_sched'), models.Index(fields=['supplier'], name='idx_appt_supplier'), models.Index(fields=['product_line'], name='idx_appt_prodline'), models.Index(fields=['status'], name='idx_appt_status'), models.Index(fields=['status', 'product_line'], name='idx_appt_status_pl')],
                'constraints': [models.CheckConstraint(condition=models.Q(('delivered_at__isnull', True), ('status', 'Entregada'), _connector='OR'), name='delivered_at_only_when_entregada')],
            },
        ),
    ]
